forbid-only: true
recursive: true
reporter: mocha-multi-reporters
reporter-options: configFile=.mocha-multi-config.json
require:
  - ts-node/register
  - dotenv/config
timeout: 5000
watch-extensions: ts
