version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm test
      - run:
          command: npm run lint:ci
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results/mocha/mocha.xml
      - store_artifacts:
          path: test-results/eslint/eslint.xml
      - store_artifacts:
          path: coverage
      - coveralls/upload
